export function TechnicalDetails(): any {
  return <section className="ipdf-section ipdf-technical" id="securite" aria-labelledby="technical-title">
    <div className="ipdf-section-head"><div><p className="ipdf-eyebrow">CE QUI SE PASSE À L’EXPORT</p><h2 id="technical-title">Un nouveau PDF,<br />reconstruit à partir des pixels.</h2></div><p>La confidentialité repose sur la façon dont le fichier est fabriqué. Voici ce que l’application conserve, ce qu’elle retire et comment vérifier le résultat.</p></div>
    <ol className="ipdf-export-steps">
      <li><span>01 · RENDU LOCAL</span><h3>Chaque page devient une image</h3><p>PDF.js dessine la page sur un canevas en mémoire, sur votre ordinateur. Toutes les pages sont reconstruites, même celles sans zone sélectionnée.</p></li>
      <li><span>02 · CAVIARDAGE DES PIXELS</span><h3>Les zones choisies sont peintes en noir</h3><p>Les rectangles sont appliqués à cette image avant son incorporation au PDF. Les limites sont arrondies vers l’extérieur au pixel près pour couvrir la sélection.</p></li>
      <li><span>03 · NOUVEAU FICHIER</span><h3>Seules les images finales sont incorporées</h3><p>pdf-lib crée un document neuf, avec une image PNG caviardée par page. Le contenu d’origine sous les zones noires n’est pas inclus dans cette nouvelle copie.</p></li>
    </ol>
    <div className="ipdf-metadata-note"><span aria-hidden="true">↳</span><div><h3>Un export sans métadonnées documentaires.</h3><p>Depuis la version 1.2.2, la copie exportée ne contient <strong>ni auteur, titre, sujet, mots-clés, créateur, producteur, ni dates de création ou de modification intégrées</strong>. Aucun dictionnaire de propriétés Info, flux XMP ou identifiant de document PDF n’est ajouté. Les métadonnées du document source ne sont pas transférées.</p></div></div>
    <div className="ipdf-technical-table"><table><caption>Ce que contient la copie exportée</caption><thead><tr><th scope="col">Dans le PDF d’origine</th><th scope="col">Dans la nouvelle copie</th></tr></thead><tbody>
      <tr><th scope="row">Texte et couche OCR cachée</th><td>Aucun objet texte d’origine. Les mots visibles hors des zones caviardées restent lisibles dans l’image et peuvent être reconnus par un nouvel OCR.</td></tr>
      <tr><th scope="row">Métadonnées et propriétés du document</th><td>Aucune propriété documentaire, date intégrée ou information sur le logiciel de création. Pas de dictionnaire Info, de flux XMP ni d’identifiant de document dans la copie.</td></tr>
      <tr><th scope="row">Pièces jointes, scripts et actions PDF</th><td>Les fichiers incorporés, JavaScript et actions du document source ne sont pas transférés.</td></tr>
      <tr><th scope="row">Formulaires, annotations et liens</th><td>Les objets interactifs sont retirés. Une apparence visible rendue sur la page peut rester dans l’image : relisez aussi les champs, commentaires visibles et adresses imprimées.</td></tr>
      <tr><th scope="row">Calques et objets d’origine</th><td>La copie contient le rendu aplati des pages, sans reprendre leurs calques, polices ou objets image source. L’aspect visible hors des zones choisies est conservé.</td></tr>
      <tr><th scope="row">Original, nom du fichier et signatures</th><td>L’original reste intact. Le nom proposé reprend celui du fichier source avec « -caviarde » : renommez-le s’il contient une information sensible. Les signatures numériques d’origine ne sont pas conservées comme signatures valides.</td></tr>
    </tbody></table></div>
    <div className="ipdf-technical-bottom">
      <article><p className="ipdf-eyebrow">DES CONTRÔLES VÉRIFIABLES</p><h3>Le fichier exporté est inspecté par les tests.</h3><p>La suite de régression utilise des PDF fictifs contenant notamment du texte caché, des métadonnées, des formulaires et des pièces jointes. Elle contrôle les pixels noirs, l’absence de texte sélectionnable et d’annotations, ainsi que l’absence de métadonnées documentaires et d’identifiant PDF. La structure est aussi contrôlée : une image aplatie par page, sans les objets sensibles du document source.</p><p>Un audit complémentaire utilise pypdf et Poppler pour examiner les fichiers produits. Ces tests documentent le comportement attendu ; ils ne constituent pas une certification de sécurité.</p><div className="ipdf-evidence-links"><a href="https://github.com/benfavre/caviard/blob/main/src/pdf.mjs">Lire le code d’export ↗</a><a href="https://github.com/benfavre/caviard/blob/main/TESTING.md">Consulter le protocole de tests ↗</a></div></article>
      <article><p className="ipdf-eyebrow">AVANT DE PARTAGER</p><h3>Vérifiez la nouvelle copie.</h3><ol><li>Ouvrez le PDF exporté et relisez toutes les pages, y compris les marges et les images.</li><li>Vérifiez que les rectangles couvrent entièrement chaque information sensible. L’IA et l’OCR peuvent manquer des éléments.</li><li>Contrôlez le nom du fichier et ses propriétés, puis partagez la copie caviardée.</li></ol><p>Le nom du fichier et les dates affichées par votre système de fichiers ne sont pas des métadonnées intégrées au PDF. L’export ne supprime pas l’original, ses sauvegardes ou les copies déjà partagées. Il ne réalise pas d’effacement sécurisé du disque.</p></article>
    </div>
    <details className="ipdf-technical-detail"><summary>Qualité du rendu, recherche et accessibilité</summary><p>Le rendu atteint 144 points par pouce pour les pages de taille courante. Il est réduit pour les très grandes pages afin de limiter le canevas à 8 192 pixels sur son côté le plus long et environ 24 millions de pixels. Les dimensions visibles des pages sont conservées.</p><p>La copie est un PDF d’images : le texte n’est plus sélectionnable ni recherchable sans un nouvel OCR. La structure sémantique, les balises d’accessibilité et l’interactivité du document d’origine ne sont pas préservées. Vérifiez la lisibilité des petits caractères et des éléments graphiques.</p></details>
    <details className="ipdf-technical-detail"><summary>Ce qui fonctionne en local et ce qui nécessite Internet</summary><p>Le rendu des pages, le caviardage, l’analyse IA et l’OCR s’exécutent sur l’ordinateur. Les modèles de l’assistant sont téléchargés avant leur première utilisation. Les documents ne sont pas envoyés à un service d’IA distant.</p><p>La connexion au compte, la gestion des crédits, le paiement, le téléchargement des modèles et les recherches de mises à jour utilisent Internet. Dans l’application de bureau, l’export nécessite un compte et des crédits disponibles.</p></details>
  </section>;
}
