// Run against `npm run dev -- --port 4175`. Records the real manual workflow.
import { chromium } from '@playwright/test';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
const out = new URL('./site/public/inklura-pdf/demos/', import.meta.url).pathname;
await mkdir(out, { recursive: true });
const pdf = await PDFDocument.create();
const font = await pdf.embedFont(StandardFonts.Helvetica);
const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
const sheet = pdf.addPage([595, 660]);
const line = (text, y, size = 14, weight = font) => sheet.drawText(text, { x: 48, y, size, font: weight, color: rgb(.09,.15,.23) });
line('ATELIER HORIZON', 603, 11, bold);
line('Proposition de mission', 548, 27, bold);
line('DOCUMENT FICTIF - DEMONSTRATION', 518, 9);
line('Client : Camille Martin', 460);
line('E-mail : camille@example.fr', 423);
line('Telephone : 01 00 00 00 00', 386);
line('Projet : accompagnement & conseil', 322);
line('Mission de conception et de suivi de projet.', 285, 12);
line('Montant : 1 200 EUR HT', 237, 16, bold);
line('Les informations utiles restent visibles.', 155, 12);
line('Donnees synthetiques. Aucun vrai dossier client.', 70, 9);
const bytes = Buffer.from(await pdf.save());
await writeFile(out + 'document-fictif.pdf', bytes);
const browser = await chromium.launch();
const context = await browser.newContext({viewport:{width:1280,height:900},recordVideo:{dir:'output/screencast',size:{width:1280,height:900}},deviceScaleFactor:1});
const page = await context.newPage();
await page.goto(process.env.DEMO_ORIGIN || 'http://127.0.0.1:4175');
await page.getByRole('button',{name:'Choisir des fichiers',exact:true}).waitFor();
const started = Date.now();
const chapters = [];
const mark = title => chapters.push({time:(Date.now()-started)/1000,title});
const pause = ms => page.waitForTimeout(ms);
mark('Importer un PDF');
await pause(1800);
await page.locator('input[type=file]').setInputFiles({name:'proposition-fictive.pdf',mimeType:'application/pdf',buffer:bytes});
await page.locator('.drawing-layer').waitFor();
await page.getByRole('button', {name:'Réduire le zoom',exact:true}).click();
await page.getByRole('button', {name:'Réduire le zoom',exact:true}).click();
await pause(2400);
await page.screenshot({path:out+'manual-poster.jpg',type:'jpeg',quality:88});
mark('Dessiner les zones');
const box = await page.locator('.drawing-layer').boundingBox();
async function draw(y) {
 const x=box.x+box.width*45/595, top=box.y+box.height*(660-y-17)/660;
 await page.mouse.move(x,top);
 await pause(450);
 await page.mouse.down();
 await page.mouse.move(x+box.width*300/595,top+box.height*24/660,{steps:45});
 await page.mouse.up();
 await pause(1700);
}
await draw(460); await draw(423); await draw(386);
mark('Ajuster et vérifier');
await page.getByRole('button',{name:'Annuler',exact:true}).click();
await pause(1500); await draw(386);
await pause(1500);
mark('Exporter la copie');
const download = page.waitForEvent('download');
await page.getByRole('button',{name:'Exporter le PDF',exact:true}).click();
await (await download).saveAs(out+'document-caviarde.pdf');
const exported = await PDFDocument.load(await readFile(out+'document-caviarde.pdf'), {updateMetadata:false});
if (exported.context.trailerInfo.Info || exported.context.trailerInfo.ID) throw new Error('Demo export contains document metadata');
await pause(3000);
const video = page.video();
await context.close();
const raw = await video.path();
await browser.close();
execFileSync('ffmpeg',['-y','-i',raw,'-an','-c:v','libx264','-preset','slow','-crf','23','-pix_fmt','yuv420p','-movflags','+faststart',out+'manual-workflow.mp4'],{stdio:'ignore'});
await writeFile(out+'chapters.json',JSON.stringify(chapters,null,2)+'\n');
console.log({chapters,raw});
