import { readFile, writeFile } from "node:fs/promises";
const records = JSON.parse(
  await readFile("output/pdf/examples/manifest.json", "utf8"),
);
const families = [...new Set(records.map((r) => r.family))];
const cards = records
  .map(
    (r) =>
      `<article data-family="${r.family}" data-name="${r.file}"><a href="examples/${r.file}" target="_blank" rel="noopener">${r.expect === "valid" ? `<img loading="lazy" src="previews/${r.file.replace(".pdf", ".png")}" alt="Preview of ${r.file}">` : `<div class="placeholder">${r.expect === "password" ? "Password protected" : "Deliberately invalid"}</div>`}<strong>${r.file}</strong></a><span>${r.family} · ${r.pages ? `${r.pages} page${r.pages > 1 ? "s" : ""}` : r.expect}</span>${r.password ? `<small>Test password: ${r.password}</small>` : ""}<a class="download" href="examples/${r.file}" download>Download PDF</a>${r.expect === "valid" ? `<a href="redacted/${r.file}" download>Download tested redacted result</a>` : ""}</article>`,
  )
  .join("");
await writeFile(
  "output/pdf/index.html",
  `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PDF redaction test collection</title><style>body{font:16px system-ui;background:#f5f7fa;color:#173047;max-width:1400px;margin:auto;padding:32px}h1{font-size:32px;margin-bottom:10px}p{line-height:1.6}a{color:#176dc0}header{margin-bottom:30px}nav{display:flex;gap:20px;flex-wrap:wrap}input,select{font:inherit;padding:12px;border:1px solid #ccd6e0;border-radius:6px;margin:15px 10px 15px 0}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:20px}article{background:white;padding:16px;border:1px solid #dce3e9;border-radius:8px;display:flex;flex-direction:column;gap:10px;font-size:13px}article img,.placeholder{width:100%;height:240px;object-fit:contain;background:#edf1f5;margin-bottom:12px}.placeholder{display:grid;place-items:center}article strong{display:block;font-size:16px}article[hidden]{display:none}small{font-family:monospace}.download{margin-top:auto}footer{margin-top:40px;color:#52677a}</style><header><h1>159 example PDFs. Real redaction tests.</h1><p>Synthetic documents covering 24 document families, 7 stress cases, 3 encrypted PDFs, and 5 deliberately invalid PDFs. All content is fictional. Valid PDFs have been exported and checked for visual fidelity and removal of original content.</p><nav><a href="example-pdfs.zip" download>Download all examples (.zip)</a><a href="examples/manifest.json">Fixture manifest</a><a href="../test-report/independent-audit.json">Independent audit</a><a href="/">Open redaction app</a></nav><label>Find a PDF <input id="search" placeholder="Search filenames"></label><label>Family <select id="family"><option value="">All families</option>${families.map((f) => `<option>${f}</option>`).join("")}</select></label><p id="count">159 documents</p></header><main>${cards}</main><footer>Generated locally. Use encrypted and invalid fixtures to verify error handling; their failure to open is intentional.</footer><script>const search=document.getElementById('search'),family=document.getElementById('family');function filter(){let count=0;for(const card of document.querySelectorAll('article')){card.hidden=!(card.dataset.name.includes(search.value.toLowerCase())&&(!family.value||card.dataset.family===family.value));if(!card.hidden)count++}document.getElementById('count').textContent=count+' documents'}search.addEventListener('input',filter);family.addEventListener('change',filter)</script></html>`,
);
console.log("Catalog: output/pdf/index.html");
